name: Send Daily Message

on:
  schedule:
    - cron: '30 19 * * *'  # UTC 기준 19:30 (한국 시간 04:30)
  workflow_dispatch:  # 수동 실행 옵션 추가

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run script
        run: python send_message.py 