name: 매일 메시지 보내기

on:
  schedule:
    - cron: '30 0 * * *'  # 매일 UTC 00:30 (한국 시간 09:30)
    - cron: '*/10 * * * *'  # 10분마다 실행
  workflow_dispatch:  # 수동 실행 가능

# 권한 설정 추가
permissions:
  contents: write

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v2
        
      - name: Python 설정
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: 의존성 설치
        run: pip install -r requirements.txt
        
      - name: 설정 업데이트
        run: python update_config.py
        
      - name: Commit and push if config changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add config.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update config.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  send-message:
    runs-on: ubuntu-latest
    # 한국 시간 09:30에만 실행되도록 조건 추가
    if: github.event.schedule == '30 0 * * *' || github.event_name == 'workflow_dispatch'
    needs: update-config  # 설정 업데이트 후 실행
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v2
        
      - name: Python 설정
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: 의존성 설치
        run: pip install -r requirements.txt
        
      - name: 메시지 보내기
        run: python send_message.py 